name: gae-ci-cd
on:
  push:
    branches: [main]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #Checking if the app build successfully
      - name: Maven install
        run: mvn clean package -DskipTests

      - name: Authenticate to Google Cloud
        id: authen-with-gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v1
        with:
          deliverables: app.yaml